spring.application.name=AI Code Analyzer
server.port=${PORT:8080}
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.code.analyzer=DEBUG

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

